# Generated by Django 3.2 on 2022-04-14 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='apiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apilfg.apimodel')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('apilfg.apimodel',),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apilfg.apimodel')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('videogame_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilfg.videogame')),
            ],
            bases=('apilfg.apimodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apilfg.apimodel')),
                ('content', models.CharField(max_length=200)),
                ('deleted', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('apilfg.apimodel',),
        ),
    ]
