# Generated by Django 3.2 on 2022-04-14 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apilfg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party_user',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apilfg.apimodel')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilfg.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('apilfg.apimodel',),
        ),
    ]
